---
title: "Data Wrangling"
author: "James Dalgleish"
date: "September 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(readr)
#setwd("data")
litters_data = readr::read_csv(file = "./data/FAS_litters.csv")
names(litters_data)
litters_data = janitor::clean_names(litters_data) #overwrite with a new version with cleaner names.
names(litters_data)
#loading pups dataset.
pups_data = janitor::clean_names(
  readr::read_csv(file = "./data/FAS_pups.csv")
)
names(pups_data)
#absolute paths
pups_data = janitor::clean_names(
  readr::read_csv(file = "C:/Users/dalgleish/Dropbox/Documents/columbia/p8105/lecture/data_import_p8105_jld2227/data/FAS_pups.csv")
)
names(pups_data)
## Look at data.

```

```{r skim}
head(litters_data)
tail(litters_data)
skimr::skim(litters_data)
View(litters_data)
```
Skip some rows & omit variable names.
```{r skip_rows_omit_var_names}
litters_data_test = read_csv(file = "./data/FAS_litters.csv",
  skip = 10, col_names = FALSE)
```
```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD12 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
```

Looking at the pups dataset:
```{r pups_column types}
pups_data = janitor::clean_names(
  readr::read_csv(file = "C:/Users/dalgleish/Dropbox/Documents/columbia/p8105/lecture/data_import_p8105_jld2227/data/FAS_pups.csv")
)
sapply(pups_data,summary)
sapply(pups_data,sd)
skimr::skim(pups_data)
```

##Other formats
read in mlb data.
```{r mlb_data}
mlb_data = janitor::clean_names(
  tibble::as.tibble(
  readxl::read_excel(path = "./data/mlb11.xlsx",range = "A1:E17")
  )
)
```

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
```

## Comparison with base R
```{r}
pups_readr = readr::read_csv("./data/FAS_pups.csv")
pups_base = read.csv("./data/FAS_pups.csv")
pups_base$S
pups_readr$Sex
```

